% This script will test the matlab pipeline from the matlab command line -
% very useful for making sure it works before we bother to compile.

matlab_entrypoint( ...
	'fmri1_nii','../../OUTPUTS/ctrrfmri1.nii', ...
	'fmri2_nii','../../OUTPUTS/ctrrfmri2.nii', ...
	'fmri3_nii','../../OUTPUTS/ctrrfmri3.nii', ...
	'fmri4_nii','../../OUTPUTS/ctrrfmri4.nii', ...
	'meanfmri_nii','../../OUTPUTS/ctrrfmri_mean_all.nii', ...
	'deffwd_nii','../../OUTPUTS/y_deffwd.nii', ...
	'refimg_nii','avg152T1.nii', ...
	'biasnorm_nii','../../OUTPUTS/biasnorm.nii', ...
	'eprime_csv','../../OUTPUTS/eprime.csv', ...
	'out_dir','../../OUTPUTS' ...
	);
