% This script will test the matlab pipeline from the matlab command line -
% very useful for making sure it works before we bother to compile.

matlab_entrypoint( ...
	'fmri1_nii','../../OUTPUTS/ctrrfmri1.nii', ...
	'fmri2_nii','../../OUTPUTS/ctrrfmri2.nii', ...
	'fmri3_nii','../../OUTPUTS/ctrrfmri3.nii', ...
	'fmri4_nii','../../OUTPUTS/ctrrfmri4.nii', ...
	'motpar1_txt','../../OUTPUTS/rfmri1.par', ...
	'motpar2_txt','../../OUTPUTS/rfmri2.par', ...
	'motpar3_txt','../../OUTPUTS/rfmri3.par', ...
	'motpar4_txt','../../OUTPUTS/rfmri4.par', ...
	'meanfmri_nii','../../OUTPUTS/ctrrfmri_mean_all.nii', ...
	'deffwd_nii','../../OUTPUTS/y_deffwd.nii', ...
	'refimg_nii','avg152T1.nii', ...
	'biasnorm_nii','../../OUTPUTS/biasnorm.nii', ...
	'trialreport_csv','../../OUTPUTS/trialreport.csv', ...
	'hpf_sec','300', ...
	'fwhm_mm','6', ...
	'out_dir','../../OUTPUTS' ...
	);
